version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ahauros-postgres
    environment:
      POSTGRES_DB: ahauros
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data-layer/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ahauros-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ahauros-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ahauros-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: ahauros-clickhouse
    environment:
      CLICKHOUSE_DB: ahauros_analytics
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: secret123
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - ahauros-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  clickhouse_data:

networks:
  ahauros-network:
    driver: bridge